/*
 * Academic License - for use in teaching, academic research, and meeting
 * course requirements at degree granting institutions only.  Not for
 * government, commercial, or other organizational use.
 *
 * FUNgen2_Basis_c.c
 *
 * Code generation for function 'FUNgen2_Basis_c'
 *
 */

/* Include files */
#include "FUNgen2_Basis_c.h"
#include "mwmathutil.h"
#include "rt_nonfinite.h"

/* Variable Definitions */
static emlrtRSInfo emlrtRSI = { 11,    /* lineNo */
  "FUNgen2_Basis_c",                   /* fcnName */
  "C:\\Users\\bencb\\Documents\\A My Documents\\A Classes\\VT\\2020 Spring\\Formal research projects\\Dynamics\\3D Pend. Ex. Matrix Featherst"
  "one\\SymbolicToCompare\\FUNgen2_Basis_c.m"/* pathName */
};

static emlrtRTEInfo emlrtRTEI = { 13,  /* lineNo */
  9,                                   /* colNo */
  "sqrt",                              /* fName */
  "C:\\Program Files\\MATLAB\\R2019b\\toolbox\\eml\\lib\\matlab\\elfun\\sqrt.m"/* pName */
};

/* Function Definitions */
void FUNgen2_Basis_c(const emlrtStack *sp, real_T fc, const real_T in2[3],
                     real_T Basis_c[12])
{
  real_T d;
  real_T d1;
  real_T d2;
  real_T a;
  real_T a_tmp;
  real_T b_a_tmp;
  real_T c_a_tmp;
  real_T b_a;
  real_T d_a_tmp;
  real_T c_a;
  real_T d_a;
  real_T e_a;
  real_T f_a;
  real_T g_a;
  real_T h_a;
  real_T i_a;
  real_T j_a;
  real_T k_a;
  real_T l_a;
  real_T m_a;
  real_T n_a;
  real_T o_a;
  real_T p_a;
  real_T q_a;
  real_T r_a;
  real_T s_a;
  real_T t_a;
  real_T u_a;
  real_T v_a;
  real_T w_a;
  real_T x_a;
  real_T y_a;
  real_T ab_a;
  real_T bb_a;
  real_T cb_a;
  real_T db_a;
  real_T eb_a;
  real_T fb_a;
  real_T gb_a;
  real_T hb_a;
  real_T ib_a;
  real_T jb_a;
  real_T kb_a;
  real_T d3;
  real_T d4;
  emlrtStack st;
  emlrtStack b_st;
  st.prev = sp;
  st.tls = sp->tls;
  b_st.prev = &st;
  b_st.tls = st.tls;

  /* FUNGEN2_BASIS_C */
  /*     BASIS_C = FUNGEN2_BASIS_C(FC,IN2) */
  /*     This function was generated by the Symbolic Math Toolbox version 8.4. */
  /*     31-Mar-2020 13:01:44 */
  st.site = &emlrtRSI;
  st.site = &emlrtRSI;
  st.site = &emlrtRSI;
  st.site = &emlrtRSI;
  st.site = &emlrtRSI;
  st.site = &emlrtRSI;
  st.site = &emlrtRSI;
  d = in2[1] * in2[1];
  d1 = in2[2] * in2[2];
  d2 = d + d1;
  b_st.site = &emlrtRSI;
  if (d2 < 0.0) {
    emlrtErrorWithMessageIdR2018a(&b_st, &emlrtRTEI,
      "Coder:toolbox:ElFunDomainError", "Coder:toolbox:ElFunDomainError", 3, 4,
      4, "sqrt");
  }

  a = in2[0] + fc * muDoubleScalarSqrt(d2);
  st.site = &emlrtRSI;
  st.site = &emlrtRSI;
  st.site = &emlrtRSI;
  st.site = &emlrtRSI;
  st.site = &emlrtRSI;
  st.site = &emlrtRSI;
  st.site = &emlrtRSI;
  st.site = &emlrtRSI;
  b_st.site = &emlrtRSI;
  if (d2 < 0.0) {
    emlrtErrorWithMessageIdR2018a(&b_st, &emlrtRTEI,
      "Coder:toolbox:ElFunDomainError", "Coder:toolbox:ElFunDomainError", 3, 4,
      4, "sqrt");
  }

  d = (in2[0] * in2[0] + d) + d1;
  b_st.site = &emlrtRSI;
  if (d < 0.0) {
    emlrtErrorWithMessageIdR2018a(&b_st, &emlrtRTEI,
      "Coder:toolbox:ElFunDomainError", "Coder:toolbox:ElFunDomainError", 3, 4,
      4, "sqrt");
  }

  a_tmp = fc * in2[0];
  b_a_tmp = fc * in2[2];
  c_a_tmp = a_tmp * in2[1];
  b_a = (in2[1] * muDoubleScalarSqrt(d2) + b_a_tmp * muDoubleScalarSqrt(d)) -
    c_a_tmp;
  st.site = &emlrtRSI;
  st.site = &emlrtRSI;
  st.site = &emlrtRSI;
  st.site = &emlrtRSI;
  st.site = &emlrtRSI;
  st.site = &emlrtRSI;
  b_st.site = &emlrtRSI;
  if (d2 < 0.0) {
    emlrtErrorWithMessageIdR2018a(&b_st, &emlrtRTEI,
      "Coder:toolbox:ElFunDomainError", "Coder:toolbox:ElFunDomainError", 3, 4,
      4, "sqrt");
  }

  b_st.site = &emlrtRSI;
  if (d < 0.0) {
    emlrtErrorWithMessageIdR2018a(&b_st, &emlrtRTEI,
      "Coder:toolbox:ElFunDomainError", "Coder:toolbox:ElFunDomainError", 3, 4,
      4, "sqrt");
  }

  d_a_tmp = fc * in2[1];
  a_tmp *= in2[2];
  c_a = (-in2[2] * muDoubleScalarSqrt(d2) + d_a_tmp * muDoubleScalarSqrt(d)) +
    a_tmp;
  st.site = &emlrtRSI;
  st.site = &emlrtRSI;
  st.site = &emlrtRSI;
  st.site = &emlrtRSI;
  st.site = &emlrtRSI;
  st.site = &emlrtRSI;
  st.site = &emlrtRSI;
  st.site = &emlrtRSI;
  b_st.site = &emlrtRSI;
  if (d2 < 0.0) {
    emlrtErrorWithMessageIdR2018a(&b_st, &emlrtRTEI,
      "Coder:toolbox:ElFunDomainError", "Coder:toolbox:ElFunDomainError", 3, 4,
      4, "sqrt");
  }

  d_a = in2[0] + fc * muDoubleScalarSqrt(d2);
  st.site = &emlrtRSI;
  st.site = &emlrtRSI;
  st.site = &emlrtRSI;
  st.site = &emlrtRSI;
  st.site = &emlrtRSI;
  st.site = &emlrtRSI;
  st.site = &emlrtRSI;
  st.site = &emlrtRSI;
  b_st.site = &emlrtRSI;
  if (d2 < 0.0) {
    emlrtErrorWithMessageIdR2018a(&b_st, &emlrtRTEI,
      "Coder:toolbox:ElFunDomainError", "Coder:toolbox:ElFunDomainError", 3, 4,
      4, "sqrt");
  }

  b_st.site = &emlrtRSI;
  if (d < 0.0) {
    emlrtErrorWithMessageIdR2018a(&b_st, &emlrtRTEI,
      "Coder:toolbox:ElFunDomainError", "Coder:toolbox:ElFunDomainError", 3, 4,
      4, "sqrt");
  }

  e_a = (in2[1] * muDoubleScalarSqrt(d2) + b_a_tmp * muDoubleScalarSqrt(d)) -
    c_a_tmp;
  st.site = &emlrtRSI;
  st.site = &emlrtRSI;
  st.site = &emlrtRSI;
  st.site = &emlrtRSI;
  st.site = &emlrtRSI;
  st.site = &emlrtRSI;
  b_st.site = &emlrtRSI;
  if (d2 < 0.0) {
    emlrtErrorWithMessageIdR2018a(&b_st, &emlrtRTEI,
      "Coder:toolbox:ElFunDomainError", "Coder:toolbox:ElFunDomainError", 3, 4,
      4, "sqrt");
  }

  b_st.site = &emlrtRSI;
  if (d < 0.0) {
    emlrtErrorWithMessageIdR2018a(&b_st, &emlrtRTEI,
      "Coder:toolbox:ElFunDomainError", "Coder:toolbox:ElFunDomainError", 3, 4,
      4, "sqrt");
  }

  f_a = (-in2[2] * muDoubleScalarSqrt(d2) + d_a_tmp * muDoubleScalarSqrt(d)) +
    a_tmp;
  st.site = &emlrtRSI;
  st.site = &emlrtRSI;
  st.site = &emlrtRSI;
  st.site = &emlrtRSI;
  st.site = &emlrtRSI;
  st.site = &emlrtRSI;
  st.site = &emlrtRSI;
  st.site = &emlrtRSI;
  b_st.site = &emlrtRSI;
  if (d2 < 0.0) {
    emlrtErrorWithMessageIdR2018a(&b_st, &emlrtRTEI,
      "Coder:toolbox:ElFunDomainError", "Coder:toolbox:ElFunDomainError", 3, 4,
      4, "sqrt");
  }

  g_a = in2[0] + fc * muDoubleScalarSqrt(d2);
  st.site = &emlrtRSI;
  st.site = &emlrtRSI;
  st.site = &emlrtRSI;
  st.site = &emlrtRSI;
  st.site = &emlrtRSI;
  st.site = &emlrtRSI;
  st.site = &emlrtRSI;
  st.site = &emlrtRSI;
  b_st.site = &emlrtRSI;
  if (d2 < 0.0) {
    emlrtErrorWithMessageIdR2018a(&b_st, &emlrtRTEI,
      "Coder:toolbox:ElFunDomainError", "Coder:toolbox:ElFunDomainError", 3, 4,
      4, "sqrt");
  }

  b_st.site = &emlrtRSI;
  if (d < 0.0) {
    emlrtErrorWithMessageIdR2018a(&b_st, &emlrtRTEI,
      "Coder:toolbox:ElFunDomainError", "Coder:toolbox:ElFunDomainError", 3, 4,
      4, "sqrt");
  }

  h_a = (in2[1] * muDoubleScalarSqrt(d2) + b_a_tmp * muDoubleScalarSqrt(d)) -
    c_a_tmp;
  st.site = &emlrtRSI;
  st.site = &emlrtRSI;
  st.site = &emlrtRSI;
  st.site = &emlrtRSI;
  st.site = &emlrtRSI;
  st.site = &emlrtRSI;
  b_st.site = &emlrtRSI;
  if (d2 < 0.0) {
    emlrtErrorWithMessageIdR2018a(&b_st, &emlrtRTEI,
      "Coder:toolbox:ElFunDomainError", "Coder:toolbox:ElFunDomainError", 3, 4,
      4, "sqrt");
  }

  b_st.site = &emlrtRSI;
  if (d < 0.0) {
    emlrtErrorWithMessageIdR2018a(&b_st, &emlrtRTEI,
      "Coder:toolbox:ElFunDomainError", "Coder:toolbox:ElFunDomainError", 3, 4,
      4, "sqrt");
  }

  i_a = (-in2[2] * muDoubleScalarSqrt(d2) + d_a_tmp * muDoubleScalarSqrt(d)) +
    a_tmp;
  st.site = &emlrtRSI;
  st.site = &emlrtRSI;
  st.site = &emlrtRSI;
  st.site = &emlrtRSI;
  st.site = &emlrtRSI;
  st.site = &emlrtRSI;
  st.site = &emlrtRSI;
  b_st.site = &emlrtRSI;
  if (d2 < 0.0) {
    emlrtErrorWithMessageIdR2018a(&b_st, &emlrtRTEI,
      "Coder:toolbox:ElFunDomainError", "Coder:toolbox:ElFunDomainError", 3, 4,
      4, "sqrt");
  }

  j_a = in2[0] + fc * muDoubleScalarSqrt(d2);
  st.site = &emlrtRSI;
  st.site = &emlrtRSI;
  st.site = &emlrtRSI;
  st.site = &emlrtRSI;
  st.site = &emlrtRSI;
  st.site = &emlrtRSI;
  st.site = &emlrtRSI;
  st.site = &emlrtRSI;
  b_st.site = &emlrtRSI;
  if (d2 < 0.0) {
    emlrtErrorWithMessageIdR2018a(&b_st, &emlrtRTEI,
      "Coder:toolbox:ElFunDomainError", "Coder:toolbox:ElFunDomainError", 3, 4,
      4, "sqrt");
  }

  b_st.site = &emlrtRSI;
  if (d < 0.0) {
    emlrtErrorWithMessageIdR2018a(&b_st, &emlrtRTEI,
      "Coder:toolbox:ElFunDomainError", "Coder:toolbox:ElFunDomainError", 3, 4,
      4, "sqrt");
  }

  k_a = (-in2[1] * muDoubleScalarSqrt(d2) + b_a_tmp * muDoubleScalarSqrt(d)) +
    c_a_tmp;
  st.site = &emlrtRSI;
  st.site = &emlrtRSI;
  st.site = &emlrtRSI;
  st.site = &emlrtRSI;
  st.site = &emlrtRSI;
  st.site = &emlrtRSI;
  b_st.site = &emlrtRSI;
  if (d2 < 0.0) {
    emlrtErrorWithMessageIdR2018a(&b_st, &emlrtRTEI,
      "Coder:toolbox:ElFunDomainError", "Coder:toolbox:ElFunDomainError", 3, 4,
      4, "sqrt");
  }

  b_st.site = &emlrtRSI;
  if (d < 0.0) {
    emlrtErrorWithMessageIdR2018a(&b_st, &emlrtRTEI,
      "Coder:toolbox:ElFunDomainError", "Coder:toolbox:ElFunDomainError", 3, 4,
      4, "sqrt");
  }

  l_a = (in2[2] * muDoubleScalarSqrt(d2) + d_a_tmp * muDoubleScalarSqrt(d)) -
    a_tmp;
  st.site = &emlrtRSI;
  st.site = &emlrtRSI;
  st.site = &emlrtRSI;
  st.site = &emlrtRSI;
  st.site = &emlrtRSI;
  st.site = &emlrtRSI;
  st.site = &emlrtRSI;
  st.site = &emlrtRSI;
  b_st.site = &emlrtRSI;
  if (d2 < 0.0) {
    emlrtErrorWithMessageIdR2018a(&b_st, &emlrtRTEI,
      "Coder:toolbox:ElFunDomainError", "Coder:toolbox:ElFunDomainError", 3, 4,
      4, "sqrt");
  }

  m_a = in2[0] + fc * muDoubleScalarSqrt(d2);
  st.site = &emlrtRSI;
  st.site = &emlrtRSI;
  st.site = &emlrtRSI;
  st.site = &emlrtRSI;
  st.site = &emlrtRSI;
  st.site = &emlrtRSI;
  st.site = &emlrtRSI;
  st.site = &emlrtRSI;
  b_st.site = &emlrtRSI;
  if (d2 < 0.0) {
    emlrtErrorWithMessageIdR2018a(&b_st, &emlrtRTEI,
      "Coder:toolbox:ElFunDomainError", "Coder:toolbox:ElFunDomainError", 3, 4,
      4, "sqrt");
  }

  b_st.site = &emlrtRSI;
  if (d < 0.0) {
    emlrtErrorWithMessageIdR2018a(&b_st, &emlrtRTEI,
      "Coder:toolbox:ElFunDomainError", "Coder:toolbox:ElFunDomainError", 3, 4,
      4, "sqrt");
  }

  n_a = (-in2[1] * muDoubleScalarSqrt(d2) + b_a_tmp * muDoubleScalarSqrt(d)) +
    c_a_tmp;
  st.site = &emlrtRSI;
  st.site = &emlrtRSI;
  st.site = &emlrtRSI;
  st.site = &emlrtRSI;
  st.site = &emlrtRSI;
  st.site = &emlrtRSI;
  b_st.site = &emlrtRSI;
  if (d2 < 0.0) {
    emlrtErrorWithMessageIdR2018a(&b_st, &emlrtRTEI,
      "Coder:toolbox:ElFunDomainError", "Coder:toolbox:ElFunDomainError", 3, 4,
      4, "sqrt");
  }

  b_st.site = &emlrtRSI;
  if (d < 0.0) {
    emlrtErrorWithMessageIdR2018a(&b_st, &emlrtRTEI,
      "Coder:toolbox:ElFunDomainError", "Coder:toolbox:ElFunDomainError", 3, 4,
      4, "sqrt");
  }

  o_a = (in2[2] * muDoubleScalarSqrt(d2) + d_a_tmp * muDoubleScalarSqrt(d)) -
    a_tmp;
  st.site = &emlrtRSI;
  st.site = &emlrtRSI;
  st.site = &emlrtRSI;
  st.site = &emlrtRSI;
  st.site = &emlrtRSI;
  st.site = &emlrtRSI;
  st.site = &emlrtRSI;
  st.site = &emlrtRSI;
  b_st.site = &emlrtRSI;
  if (d2 < 0.0) {
    emlrtErrorWithMessageIdR2018a(&b_st, &emlrtRTEI,
      "Coder:toolbox:ElFunDomainError", "Coder:toolbox:ElFunDomainError", 3, 4,
      4, "sqrt");
  }

  p_a = in2[0] + fc * muDoubleScalarSqrt(d2);
  st.site = &emlrtRSI;
  st.site = &emlrtRSI;
  st.site = &emlrtRSI;
  st.site = &emlrtRSI;
  st.site = &emlrtRSI;
  st.site = &emlrtRSI;
  st.site = &emlrtRSI;
  st.site = &emlrtRSI;
  b_st.site = &emlrtRSI;
  if (d2 < 0.0) {
    emlrtErrorWithMessageIdR2018a(&b_st, &emlrtRTEI,
      "Coder:toolbox:ElFunDomainError", "Coder:toolbox:ElFunDomainError", 3, 4,
      4, "sqrt");
  }

  b_st.site = &emlrtRSI;
  if (d < 0.0) {
    emlrtErrorWithMessageIdR2018a(&b_st, &emlrtRTEI,
      "Coder:toolbox:ElFunDomainError", "Coder:toolbox:ElFunDomainError", 3, 4,
      4, "sqrt");
  }

  q_a = (-in2[1] * muDoubleScalarSqrt(d2) + b_a_tmp * muDoubleScalarSqrt(d)) +
    c_a_tmp;
  st.site = &emlrtRSI;
  st.site = &emlrtRSI;
  st.site = &emlrtRSI;
  st.site = &emlrtRSI;
  st.site = &emlrtRSI;
  st.site = &emlrtRSI;
  b_st.site = &emlrtRSI;
  if (d2 < 0.0) {
    emlrtErrorWithMessageIdR2018a(&b_st, &emlrtRTEI,
      "Coder:toolbox:ElFunDomainError", "Coder:toolbox:ElFunDomainError", 3, 4,
      4, "sqrt");
  }

  b_st.site = &emlrtRSI;
  if (d < 0.0) {
    emlrtErrorWithMessageIdR2018a(&b_st, &emlrtRTEI,
      "Coder:toolbox:ElFunDomainError", "Coder:toolbox:ElFunDomainError", 3, 4,
      4, "sqrt");
  }

  r_a = (in2[2] * muDoubleScalarSqrt(d2) + d_a_tmp * muDoubleScalarSqrt(d)) -
    a_tmp;
  st.site = &emlrtRSI;
  st.site = &emlrtRSI;
  st.site = &emlrtRSI;
  st.site = &emlrtRSI;
  st.site = &emlrtRSI;
  st.site = &emlrtRSI;
  st.site = &emlrtRSI;
  b_st.site = &emlrtRSI;
  if (d2 < 0.0) {
    emlrtErrorWithMessageIdR2018a(&b_st, &emlrtRTEI,
      "Coder:toolbox:ElFunDomainError", "Coder:toolbox:ElFunDomainError", 3, 4,
      4, "sqrt");
  }

  s_a = in2[0] - fc * muDoubleScalarSqrt(d2);
  st.site = &emlrtRSI;
  st.site = &emlrtRSI;
  st.site = &emlrtRSI;
  st.site = &emlrtRSI;
  st.site = &emlrtRSI;
  st.site = &emlrtRSI;
  st.site = &emlrtRSI;
  st.site = &emlrtRSI;
  b_st.site = &emlrtRSI;
  if (d2 < 0.0) {
    emlrtErrorWithMessageIdR2018a(&b_st, &emlrtRTEI,
      "Coder:toolbox:ElFunDomainError", "Coder:toolbox:ElFunDomainError", 3, 4,
      4, "sqrt");
  }

  b_st.site = &emlrtRSI;
  if (d < 0.0) {
    emlrtErrorWithMessageIdR2018a(&b_st, &emlrtRTEI,
      "Coder:toolbox:ElFunDomainError", "Coder:toolbox:ElFunDomainError", 3, 4,
      4, "sqrt");
  }

  t_a = (in2[1] * muDoubleScalarSqrt(d2) - b_a_tmp * muDoubleScalarSqrt(d)) +
    c_a_tmp;
  st.site = &emlrtRSI;
  st.site = &emlrtRSI;
  st.site = &emlrtRSI;
  st.site = &emlrtRSI;
  st.site = &emlrtRSI;
  st.site = &emlrtRSI;
  b_st.site = &emlrtRSI;
  if (d2 < 0.0) {
    emlrtErrorWithMessageIdR2018a(&b_st, &emlrtRTEI,
      "Coder:toolbox:ElFunDomainError", "Coder:toolbox:ElFunDomainError", 3, 4,
      4, "sqrt");
  }

  b_st.site = &emlrtRSI;
  if (d < 0.0) {
    emlrtErrorWithMessageIdR2018a(&b_st, &emlrtRTEI,
      "Coder:toolbox:ElFunDomainError", "Coder:toolbox:ElFunDomainError", 3, 4,
      4, "sqrt");
  }

  u_a = (in2[2] * muDoubleScalarSqrt(d2) + d_a_tmp * muDoubleScalarSqrt(d)) +
    a_tmp;
  st.site = &emlrtRSI;
  st.site = &emlrtRSI;
  st.site = &emlrtRSI;
  st.site = &emlrtRSI;
  st.site = &emlrtRSI;
  st.site = &emlrtRSI;
  st.site = &emlrtRSI;
  st.site = &emlrtRSI;
  b_st.site = &emlrtRSI;
  if (d2 < 0.0) {
    emlrtErrorWithMessageIdR2018a(&b_st, &emlrtRTEI,
      "Coder:toolbox:ElFunDomainError", "Coder:toolbox:ElFunDomainError", 3, 4,
      4, "sqrt");
  }

  v_a = in2[0] - fc * muDoubleScalarSqrt(d2);
  st.site = &emlrtRSI;
  st.site = &emlrtRSI;
  st.site = &emlrtRSI;
  st.site = &emlrtRSI;
  st.site = &emlrtRSI;
  st.site = &emlrtRSI;
  st.site = &emlrtRSI;
  st.site = &emlrtRSI;
  b_st.site = &emlrtRSI;
  if (d2 < 0.0) {
    emlrtErrorWithMessageIdR2018a(&b_st, &emlrtRTEI,
      "Coder:toolbox:ElFunDomainError", "Coder:toolbox:ElFunDomainError", 3, 4,
      4, "sqrt");
  }

  b_st.site = &emlrtRSI;
  if (d < 0.0) {
    emlrtErrorWithMessageIdR2018a(&b_st, &emlrtRTEI,
      "Coder:toolbox:ElFunDomainError", "Coder:toolbox:ElFunDomainError", 3, 4,
      4, "sqrt");
  }

  w_a = (in2[1] * muDoubleScalarSqrt(d2) - b_a_tmp * muDoubleScalarSqrt(d)) +
    c_a_tmp;
  st.site = &emlrtRSI;
  st.site = &emlrtRSI;
  st.site = &emlrtRSI;
  st.site = &emlrtRSI;
  st.site = &emlrtRSI;
  st.site = &emlrtRSI;
  b_st.site = &emlrtRSI;
  if (d2 < 0.0) {
    emlrtErrorWithMessageIdR2018a(&b_st, &emlrtRTEI,
      "Coder:toolbox:ElFunDomainError", "Coder:toolbox:ElFunDomainError", 3, 4,
      4, "sqrt");
  }

  b_st.site = &emlrtRSI;
  if (d < 0.0) {
    emlrtErrorWithMessageIdR2018a(&b_st, &emlrtRTEI,
      "Coder:toolbox:ElFunDomainError", "Coder:toolbox:ElFunDomainError", 3, 4,
      4, "sqrt");
  }

  x_a = (in2[2] * muDoubleScalarSqrt(d2) + d_a_tmp * muDoubleScalarSqrt(d)) +
    a_tmp;
  st.site = &emlrtRSI;
  st.site = &emlrtRSI;
  st.site = &emlrtRSI;
  st.site = &emlrtRSI;
  st.site = &emlrtRSI;
  st.site = &emlrtRSI;
  st.site = &emlrtRSI;
  st.site = &emlrtRSI;
  b_st.site = &emlrtRSI;
  if (d2 < 0.0) {
    emlrtErrorWithMessageIdR2018a(&b_st, &emlrtRTEI,
      "Coder:toolbox:ElFunDomainError", "Coder:toolbox:ElFunDomainError", 3, 4,
      4, "sqrt");
  }

  y_a = in2[0] - fc * muDoubleScalarSqrt(d2);
  st.site = &emlrtRSI;
  st.site = &emlrtRSI;
  st.site = &emlrtRSI;
  st.site = &emlrtRSI;
  st.site = &emlrtRSI;
  st.site = &emlrtRSI;
  st.site = &emlrtRSI;
  st.site = &emlrtRSI;
  b_st.site = &emlrtRSI;
  if (d2 < 0.0) {
    emlrtErrorWithMessageIdR2018a(&b_st, &emlrtRTEI,
      "Coder:toolbox:ElFunDomainError", "Coder:toolbox:ElFunDomainError", 3, 4,
      4, "sqrt");
  }

  b_st.site = &emlrtRSI;
  if (d < 0.0) {
    emlrtErrorWithMessageIdR2018a(&b_st, &emlrtRTEI,
      "Coder:toolbox:ElFunDomainError", "Coder:toolbox:ElFunDomainError", 3, 4,
      4, "sqrt");
  }

  ab_a = (in2[1] * muDoubleScalarSqrt(d2) - b_a_tmp * muDoubleScalarSqrt(d)) +
    c_a_tmp;
  st.site = &emlrtRSI;
  st.site = &emlrtRSI;
  st.site = &emlrtRSI;
  st.site = &emlrtRSI;
  st.site = &emlrtRSI;
  st.site = &emlrtRSI;
  b_st.site = &emlrtRSI;
  if (d2 < 0.0) {
    emlrtErrorWithMessageIdR2018a(&b_st, &emlrtRTEI,
      "Coder:toolbox:ElFunDomainError", "Coder:toolbox:ElFunDomainError", 3, 4,
      4, "sqrt");
  }

  b_st.site = &emlrtRSI;
  if (d < 0.0) {
    emlrtErrorWithMessageIdR2018a(&b_st, &emlrtRTEI,
      "Coder:toolbox:ElFunDomainError", "Coder:toolbox:ElFunDomainError", 3, 4,
      4, "sqrt");
  }

  bb_a = (in2[2] * muDoubleScalarSqrt(d2) + d_a_tmp * muDoubleScalarSqrt(d)) +
    a_tmp;
  st.site = &emlrtRSI;
  st.site = &emlrtRSI;
  st.site = &emlrtRSI;
  st.site = &emlrtRSI;
  st.site = &emlrtRSI;
  st.site = &emlrtRSI;
  st.site = &emlrtRSI;
  b_st.site = &emlrtRSI;
  if (d2 < 0.0) {
    emlrtErrorWithMessageIdR2018a(&b_st, &emlrtRTEI,
      "Coder:toolbox:ElFunDomainError", "Coder:toolbox:ElFunDomainError", 3, 4,
      4, "sqrt");
  }

  cb_a = in2[0] - fc * muDoubleScalarSqrt(d2);
  st.site = &emlrtRSI;
  st.site = &emlrtRSI;
  st.site = &emlrtRSI;
  st.site = &emlrtRSI;
  st.site = &emlrtRSI;
  st.site = &emlrtRSI;
  st.site = &emlrtRSI;
  st.site = &emlrtRSI;
  b_st.site = &emlrtRSI;
  if (d2 < 0.0) {
    emlrtErrorWithMessageIdR2018a(&b_st, &emlrtRTEI,
      "Coder:toolbox:ElFunDomainError", "Coder:toolbox:ElFunDomainError", 3, 4,
      4, "sqrt");
  }

  b_st.site = &emlrtRSI;
  if (d < 0.0) {
    emlrtErrorWithMessageIdR2018a(&b_st, &emlrtRTEI,
      "Coder:toolbox:ElFunDomainError", "Coder:toolbox:ElFunDomainError", 3, 4,
      4, "sqrt");
  }

  db_a = (in2[1] * muDoubleScalarSqrt(d2) + b_a_tmp * muDoubleScalarSqrt(d)) +
    c_a_tmp;
  st.site = &emlrtRSI;
  st.site = &emlrtRSI;
  st.site = &emlrtRSI;
  st.site = &emlrtRSI;
  st.site = &emlrtRSI;
  st.site = &emlrtRSI;
  b_st.site = &emlrtRSI;
  if (d2 < 0.0) {
    emlrtErrorWithMessageIdR2018a(&b_st, &emlrtRTEI,
      "Coder:toolbox:ElFunDomainError", "Coder:toolbox:ElFunDomainError", 3, 4,
      4, "sqrt");
  }

  b_st.site = &emlrtRSI;
  if (d < 0.0) {
    emlrtErrorWithMessageIdR2018a(&b_st, &emlrtRTEI,
      "Coder:toolbox:ElFunDomainError", "Coder:toolbox:ElFunDomainError", 3, 4,
      4, "sqrt");
  }

  eb_a = (in2[2] * muDoubleScalarSqrt(d2) - d_a_tmp * muDoubleScalarSqrt(d)) +
    a_tmp;
  st.site = &emlrtRSI;
  st.site = &emlrtRSI;
  st.site = &emlrtRSI;
  st.site = &emlrtRSI;
  st.site = &emlrtRSI;
  st.site = &emlrtRSI;
  st.site = &emlrtRSI;
  st.site = &emlrtRSI;
  b_st.site = &emlrtRSI;
  if (d2 < 0.0) {
    emlrtErrorWithMessageIdR2018a(&b_st, &emlrtRTEI,
      "Coder:toolbox:ElFunDomainError", "Coder:toolbox:ElFunDomainError", 3, 4,
      4, "sqrt");
  }

  fb_a = in2[0] - fc * muDoubleScalarSqrt(d2);
  st.site = &emlrtRSI;
  st.site = &emlrtRSI;
  st.site = &emlrtRSI;
  st.site = &emlrtRSI;
  st.site = &emlrtRSI;
  st.site = &emlrtRSI;
  st.site = &emlrtRSI;
  st.site = &emlrtRSI;
  b_st.site = &emlrtRSI;
  if (d2 < 0.0) {
    emlrtErrorWithMessageIdR2018a(&b_st, &emlrtRTEI,
      "Coder:toolbox:ElFunDomainError", "Coder:toolbox:ElFunDomainError", 3, 4,
      4, "sqrt");
  }

  b_st.site = &emlrtRSI;
  if (d < 0.0) {
    emlrtErrorWithMessageIdR2018a(&b_st, &emlrtRTEI,
      "Coder:toolbox:ElFunDomainError", "Coder:toolbox:ElFunDomainError", 3, 4,
      4, "sqrt");
  }

  gb_a = (in2[1] * muDoubleScalarSqrt(d2) + b_a_tmp * muDoubleScalarSqrt(d)) +
    c_a_tmp;
  st.site = &emlrtRSI;
  st.site = &emlrtRSI;
  st.site = &emlrtRSI;
  st.site = &emlrtRSI;
  st.site = &emlrtRSI;
  st.site = &emlrtRSI;
  b_st.site = &emlrtRSI;
  if (d2 < 0.0) {
    emlrtErrorWithMessageIdR2018a(&b_st, &emlrtRTEI,
      "Coder:toolbox:ElFunDomainError", "Coder:toolbox:ElFunDomainError", 3, 4,
      4, "sqrt");
  }

  b_st.site = &emlrtRSI;
  if (d < 0.0) {
    emlrtErrorWithMessageIdR2018a(&b_st, &emlrtRTEI,
      "Coder:toolbox:ElFunDomainError", "Coder:toolbox:ElFunDomainError", 3, 4,
      4, "sqrt");
  }

  hb_a = (in2[2] * muDoubleScalarSqrt(d2) - d_a_tmp * muDoubleScalarSqrt(d)) +
    a_tmp;
  st.site = &emlrtRSI;
  st.site = &emlrtRSI;
  st.site = &emlrtRSI;
  st.site = &emlrtRSI;
  st.site = &emlrtRSI;
  st.site = &emlrtRSI;
  st.site = &emlrtRSI;
  st.site = &emlrtRSI;
  b_st.site = &emlrtRSI;
  if (d2 < 0.0) {
    emlrtErrorWithMessageIdR2018a(&b_st, &emlrtRTEI,
      "Coder:toolbox:ElFunDomainError", "Coder:toolbox:ElFunDomainError", 3, 4,
      4, "sqrt");
  }

  ib_a = in2[0] - fc * muDoubleScalarSqrt(d2);
  st.site = &emlrtRSI;
  st.site = &emlrtRSI;
  st.site = &emlrtRSI;
  st.site = &emlrtRSI;
  st.site = &emlrtRSI;
  st.site = &emlrtRSI;
  st.site = &emlrtRSI;
  st.site = &emlrtRSI;
  b_st.site = &emlrtRSI;
  if (d2 < 0.0) {
    emlrtErrorWithMessageIdR2018a(&b_st, &emlrtRTEI,
      "Coder:toolbox:ElFunDomainError", "Coder:toolbox:ElFunDomainError", 3, 4,
      4, "sqrt");
  }

  b_st.site = &emlrtRSI;
  if (d < 0.0) {
    emlrtErrorWithMessageIdR2018a(&b_st, &emlrtRTEI,
      "Coder:toolbox:ElFunDomainError", "Coder:toolbox:ElFunDomainError", 3, 4,
      4, "sqrt");
  }

  jb_a = (in2[1] * muDoubleScalarSqrt(d2) + b_a_tmp * muDoubleScalarSqrt(d)) +
    c_a_tmp;
  st.site = &emlrtRSI;
  st.site = &emlrtRSI;
  st.site = &emlrtRSI;
  st.site = &emlrtRSI;
  st.site = &emlrtRSI;
  st.site = &emlrtRSI;
  b_st.site = &emlrtRSI;
  if (d2 < 0.0) {
    emlrtErrorWithMessageIdR2018a(&b_st, &emlrtRTEI,
      "Coder:toolbox:ElFunDomainError", "Coder:toolbox:ElFunDomainError", 3, 4,
      4, "sqrt");
  }

  b_st.site = &emlrtRSI;
  if (d < 0.0) {
    emlrtErrorWithMessageIdR2018a(&b_st, &emlrtRTEI,
      "Coder:toolbox:ElFunDomainError", "Coder:toolbox:ElFunDomainError", 3, 4,
      4, "sqrt");
  }

  kb_a = (in2[2] * muDoubleScalarSqrt(d2) - d_a_tmp * muDoubleScalarSqrt(d)) +
    a_tmp;
  st.site = &emlrtRSI;
  if (d2 < 0.0) {
    emlrtErrorWithMessageIdR2018a(&st, &emlrtRTEI,
      "Coder:toolbox:ElFunDomainError", "Coder:toolbox:ElFunDomainError", 3, 4,
      4, "sqrt");
  }

  d1 = (a * a * d2 + b_a * b_a) + c_a * c_a;
  st.site = &emlrtRSI;
  if (d1 < 0.0) {
    emlrtErrorWithMessageIdR2018a(&st, &emlrtRTEI,
      "Coder:toolbox:ElFunDomainError", "Coder:toolbox:ElFunDomainError", 3, 4,
      4, "sqrt");
  }

  d1 = muDoubleScalarSqrt(d1);
  st.site = &emlrtRSI;
  if (d2 < 0.0) {
    emlrtErrorWithMessageIdR2018a(&st, &emlrtRTEI,
      "Coder:toolbox:ElFunDomainError", "Coder:toolbox:ElFunDomainError", 3, 4,
      4, "sqrt");
  }

  st.site = &emlrtRSI;
  if (d < 0.0) {
    emlrtErrorWithMessageIdR2018a(&st, &emlrtRTEI,
      "Coder:toolbox:ElFunDomainError", "Coder:toolbox:ElFunDomainError", 3, 4,
      4, "sqrt");
  }

  d3 = (d_a * d_a * d2 + e_a * e_a) + f_a * f_a;
  st.site = &emlrtRSI;
  if (d3 < 0.0) {
    emlrtErrorWithMessageIdR2018a(&st, &emlrtRTEI,
      "Coder:toolbox:ElFunDomainError", "Coder:toolbox:ElFunDomainError", 3, 4,
      4, "sqrt");
  }

  d3 = muDoubleScalarSqrt(d3);
  st.site = &emlrtRSI;
  if (d2 < 0.0) {
    emlrtErrorWithMessageIdR2018a(&st, &emlrtRTEI,
      "Coder:toolbox:ElFunDomainError", "Coder:toolbox:ElFunDomainError", 3, 4,
      4, "sqrt");
  }

  st.site = &emlrtRSI;
  if (d < 0.0) {
    emlrtErrorWithMessageIdR2018a(&st, &emlrtRTEI,
      "Coder:toolbox:ElFunDomainError", "Coder:toolbox:ElFunDomainError", 3, 4,
      4, "sqrt");
  }

  d4 = (g_a * g_a * d2 + h_a * h_a) + i_a * i_a;
  st.site = &emlrtRSI;
  if (d4 < 0.0) {
    emlrtErrorWithMessageIdR2018a(&st, &emlrtRTEI,
      "Coder:toolbox:ElFunDomainError", "Coder:toolbox:ElFunDomainError", 3, 4,
      4, "sqrt");
  }

  d4 = muDoubleScalarSqrt(d4);
  st.site = &emlrtRSI;
  if (d2 < 0.0) {
    emlrtErrorWithMessageIdR2018a(&st, &emlrtRTEI,
      "Coder:toolbox:ElFunDomainError", "Coder:toolbox:ElFunDomainError", 3, 4,
      4, "sqrt");
  }

  j_a = (j_a * j_a * d2 + k_a * k_a) + l_a * l_a;
  st.site = &emlrtRSI;
  if (j_a < 0.0) {
    emlrtErrorWithMessageIdR2018a(&st, &emlrtRTEI,
      "Coder:toolbox:ElFunDomainError", "Coder:toolbox:ElFunDomainError", 3, 4,
      4, "sqrt");
  }

  j_a = muDoubleScalarSqrt(j_a);
  st.site = &emlrtRSI;
  if (d2 < 0.0) {
    emlrtErrorWithMessageIdR2018a(&st, &emlrtRTEI,
      "Coder:toolbox:ElFunDomainError", "Coder:toolbox:ElFunDomainError", 3, 4,
      4, "sqrt");
  }

  st.site = &emlrtRSI;
  if (d < 0.0) {
    emlrtErrorWithMessageIdR2018a(&st, &emlrtRTEI,
      "Coder:toolbox:ElFunDomainError", "Coder:toolbox:ElFunDomainError", 3, 4,
      4, "sqrt");
  }

  i_a = (m_a * m_a * d2 + n_a * n_a) + o_a * o_a;
  st.site = &emlrtRSI;
  if (i_a < 0.0) {
    emlrtErrorWithMessageIdR2018a(&st, &emlrtRTEI,
      "Coder:toolbox:ElFunDomainError", "Coder:toolbox:ElFunDomainError", 3, 4,
      4, "sqrt");
  }

  i_a = muDoubleScalarSqrt(i_a);
  st.site = &emlrtRSI;
  if (d2 < 0.0) {
    emlrtErrorWithMessageIdR2018a(&st, &emlrtRTEI,
      "Coder:toolbox:ElFunDomainError", "Coder:toolbox:ElFunDomainError", 3, 4,
      4, "sqrt");
  }

  st.site = &emlrtRSI;
  if (d < 0.0) {
    emlrtErrorWithMessageIdR2018a(&st, &emlrtRTEI,
      "Coder:toolbox:ElFunDomainError", "Coder:toolbox:ElFunDomainError", 3, 4,
      4, "sqrt");
  }

  h_a = (p_a * p_a * d2 + q_a * q_a) + r_a * r_a;
  st.site = &emlrtRSI;
  if (h_a < 0.0) {
    emlrtErrorWithMessageIdR2018a(&st, &emlrtRTEI,
      "Coder:toolbox:ElFunDomainError", "Coder:toolbox:ElFunDomainError", 3, 4,
      4, "sqrt");
  }

  h_a = muDoubleScalarSqrt(h_a);
  st.site = &emlrtRSI;
  if (d2 < 0.0) {
    emlrtErrorWithMessageIdR2018a(&st, &emlrtRTEI,
      "Coder:toolbox:ElFunDomainError", "Coder:toolbox:ElFunDomainError", 3, 4,
      4, "sqrt");
  }

  g_a = (s_a * s_a * d2 + t_a * t_a) + u_a * u_a;
  st.site = &emlrtRSI;
  if (g_a < 0.0) {
    emlrtErrorWithMessageIdR2018a(&st, &emlrtRTEI,
      "Coder:toolbox:ElFunDomainError", "Coder:toolbox:ElFunDomainError", 3, 4,
      4, "sqrt");
  }

  g_a = muDoubleScalarSqrt(g_a);
  st.site = &emlrtRSI;
  if (d2 < 0.0) {
    emlrtErrorWithMessageIdR2018a(&st, &emlrtRTEI,
      "Coder:toolbox:ElFunDomainError", "Coder:toolbox:ElFunDomainError", 3, 4,
      4, "sqrt");
  }

  st.site = &emlrtRSI;
  if (d < 0.0) {
    emlrtErrorWithMessageIdR2018a(&st, &emlrtRTEI,
      "Coder:toolbox:ElFunDomainError", "Coder:toolbox:ElFunDomainError", 3, 4,
      4, "sqrt");
  }

  f_a = (v_a * v_a * d2 + w_a * w_a) + x_a * x_a;
  st.site = &emlrtRSI;
  if (f_a < 0.0) {
    emlrtErrorWithMessageIdR2018a(&st, &emlrtRTEI,
      "Coder:toolbox:ElFunDomainError", "Coder:toolbox:ElFunDomainError", 3, 4,
      4, "sqrt");
  }

  f_a = muDoubleScalarSqrt(f_a);
  st.site = &emlrtRSI;
  if (d2 < 0.0) {
    emlrtErrorWithMessageIdR2018a(&st, &emlrtRTEI,
      "Coder:toolbox:ElFunDomainError", "Coder:toolbox:ElFunDomainError", 3, 4,
      4, "sqrt");
  }

  st.site = &emlrtRSI;
  if (d < 0.0) {
    emlrtErrorWithMessageIdR2018a(&st, &emlrtRTEI,
      "Coder:toolbox:ElFunDomainError", "Coder:toolbox:ElFunDomainError", 3, 4,
      4, "sqrt");
  }

  e_a = (y_a * y_a * d2 + ab_a * ab_a) + bb_a * bb_a;
  st.site = &emlrtRSI;
  if (e_a < 0.0) {
    emlrtErrorWithMessageIdR2018a(&st, &emlrtRTEI,
      "Coder:toolbox:ElFunDomainError", "Coder:toolbox:ElFunDomainError", 3, 4,
      4, "sqrt");
  }

  e_a = muDoubleScalarSqrt(e_a);
  st.site = &emlrtRSI;
  if (d2 < 0.0) {
    emlrtErrorWithMessageIdR2018a(&st, &emlrtRTEI,
      "Coder:toolbox:ElFunDomainError", "Coder:toolbox:ElFunDomainError", 3, 4,
      4, "sqrt");
  }

  d_a = (cb_a * cb_a * d2 + db_a * db_a) + eb_a * eb_a;
  st.site = &emlrtRSI;
  if (d_a < 0.0) {
    emlrtErrorWithMessageIdR2018a(&st, &emlrtRTEI,
      "Coder:toolbox:ElFunDomainError", "Coder:toolbox:ElFunDomainError", 3, 4,
      4, "sqrt");
  }

  d_a = muDoubleScalarSqrt(d_a);
  st.site = &emlrtRSI;
  if (d2 < 0.0) {
    emlrtErrorWithMessageIdR2018a(&st, &emlrtRTEI,
      "Coder:toolbox:ElFunDomainError", "Coder:toolbox:ElFunDomainError", 3, 4,
      4, "sqrt");
  }

  st.site = &emlrtRSI;
  if (d < 0.0) {
    emlrtErrorWithMessageIdR2018a(&st, &emlrtRTEI,
      "Coder:toolbox:ElFunDomainError", "Coder:toolbox:ElFunDomainError", 3, 4,
      4, "sqrt");
  }

  a = (fb_a * fb_a * d2 + gb_a * gb_a) + hb_a * hb_a;
  st.site = &emlrtRSI;
  if (a < 0.0) {
    emlrtErrorWithMessageIdR2018a(&st, &emlrtRTEI,
      "Coder:toolbox:ElFunDomainError", "Coder:toolbox:ElFunDomainError", 3, 4,
      4, "sqrt");
  }

  a = muDoubleScalarSqrt(a);
  st.site = &emlrtRSI;
  if (d2 < 0.0) {
    emlrtErrorWithMessageIdR2018a(&st, &emlrtRTEI,
      "Coder:toolbox:ElFunDomainError", "Coder:toolbox:ElFunDomainError", 3, 4,
      4, "sqrt");
  }

  st.site = &emlrtRSI;
  if (d < 0.0) {
    emlrtErrorWithMessageIdR2018a(&st, &emlrtRTEI,
      "Coder:toolbox:ElFunDomainError", "Coder:toolbox:ElFunDomainError", 3, 4,
      4, "sqrt");
  }

  b_a = (ib_a * ib_a * d2 + jb_a * jb_a) + kb_a * kb_a;
  st.site = &emlrtRSI;
  if (b_a < 0.0) {
    emlrtErrorWithMessageIdR2018a(&st, &emlrtRTEI,
      "Coder:toolbox:ElFunDomainError", "Coder:toolbox:ElFunDomainError", 3, 4,
      4, "sqrt");
  }

  b_a = muDoubleScalarSqrt(b_a);
  c_a = fc * d2;
  Basis_c[0] = (in2[0] * muDoubleScalarSqrt(d2) + c_a) / d1;
  Basis_c[1] = ((in2[1] * muDoubleScalarSqrt(d2) + b_a_tmp * muDoubleScalarSqrt
                 (d)) - c_a_tmp) / d3;
  Basis_c[2] = -((-in2[2] * muDoubleScalarSqrt(d2) + d_a_tmp *
                  muDoubleScalarSqrt(d)) + a_tmp) / d4;
  Basis_c[3] = (in2[0] * muDoubleScalarSqrt(d2) + c_a) / j_a;
  Basis_c[4] = -((-in2[1] * muDoubleScalarSqrt(d2) + b_a_tmp *
                  muDoubleScalarSqrt(d)) + c_a_tmp) / i_a;
  Basis_c[5] = ((in2[2] * muDoubleScalarSqrt(d2) + d_a_tmp * muDoubleScalarSqrt
                 (d)) - a_tmp) / h_a;
  Basis_c[6] = (in2[0] * muDoubleScalarSqrt(d2) - c_a) / g_a;
  Basis_c[7] = ((in2[1] * muDoubleScalarSqrt(d2) - b_a_tmp * muDoubleScalarSqrt
                 (d)) + c_a_tmp) / f_a;
  Basis_c[8] = ((in2[2] * muDoubleScalarSqrt(d2) + d_a_tmp * muDoubleScalarSqrt
                 (d)) + a_tmp) / e_a;
  Basis_c[9] = (in2[0] * muDoubleScalarSqrt(d2) - c_a) / d_a;
  Basis_c[10] = ((in2[1] * muDoubleScalarSqrt(d2) + b_a_tmp * muDoubleScalarSqrt
                  (d)) + c_a_tmp) / a;
  Basis_c[11] = ((in2[2] * muDoubleScalarSqrt(d2) - d_a_tmp * muDoubleScalarSqrt
                  (d)) + a_tmp) / b_a;
}

/* End of code generation (FUNgen2_Basis_c.c) */
